### 1. 

En el archivo "logistic_regression_df_class" hemos visto un ejemplo multiclase. Elimina del dataframe todas las filas que se correspondan con la clase valor "1".

Ahora, realiza el ejercicio con el nuevo dataframe:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema (probar al menos 2 diferentes)

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html


### Sí se mejora la precisión del algoritmo. el porcentaje de aciertos con 3 valores en la variable clase es: 0.7823529411764706 y eliminando el valor 1 es: 0.9538461538461539. También mejora en la muestra de entrenamiento y en la de test

### Creo que se mejora porque la variable se queda con valores más diferenciados al eliminar el 1 con lo que es más fácil la predicción

### Con los dos nuevos parámetros que he probado: liblinear y newton-cg no se modifica el porcentaje de aciertos 

In [19]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
#from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb

In [20]:
dataframe = pd.read_csv("../data/usuarios_win_mac_lin.csv")

In [21]:
# Eliminar de la variable clase el valor 1
filtro = dataframe['clase'] != 1
dataframe = dataframe[filtro]


In [22]:
# obtener los valores únicos de la variable clase después de eliminar el valor 1
dataframe['clase'].unique()

array([2, 0], dtype=int64)

### Creamos el modelo

In [23]:
X = np.array(dataframe.drop(['clase'], axis=1))
y = np.array(dataframe['clase'])
print(y.shape)
X.shape

(130,)


(130, 4)

In [24]:
model = linear_model.LogisticRegression(max_iter=100)
# No se está entrenado con el conjunto de entrenamiento
model.fit(X,y)
model.score(X, y)

0.9538461538461539

In [25]:
y_predict = model.predict(X)

### Validamos el modelo

In [29]:
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)
print(X_train.shape)
X_test.shape

(104, 4)


(26, 4)

In [33]:
model = linear_model.LogisticRegression(max_iter=100)
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())
print(cv_results)
print("----------")
print(msg)

[0.85714286 0.91428571 0.97058824]
----------
Logistic Regression: 0.914006 +- (0.046314)


In [35]:
model.fit(X_train, Y_train)

LogisticRegression()

In [36]:
model.score(X_train, Y_train)

0.9519230769230769

In [37]:
model.score(X_test, Y_test)

0.9615384615384616

In [38]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

0.9615384615384616
0.9615384615384616


In [39]:
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 96.15 %
Error: 3.85 %


In [40]:
print(confusion_matrix(Y_test, predictions))

[[22  1]
 [ 0  3]]


## Algoritmo alternativo para optimizar el modelo: liblinear

In [59]:
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)
print(X_train.shape)
X_test.shape

(104, 4)


(26, 4)

In [60]:
model = linear_model.LogisticRegression(max_iter=100, solver='liblinear')
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())

In [61]:
model.fit(X_train, Y_train)

LogisticRegression(solver='liblinear')

In [62]:
model.score(X_train, Y_train)

0.9519230769230769

In [63]:
model.score(X_test, Y_test)

0.9615384615384616

In [64]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

0.9615384615384616
0.9615384615384616


In [65]:
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 96.15 %
Error: 3.85 %


## Algoritmo alternativo para optimizar el modelo: newton-cg

In [66]:
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)
print(X_train.shape)
X_test.shape

(104, 4)


(26, 4)

In [67]:
model = linear_model.LogisticRegression(max_iter=100, solver='newton-cg')
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())

In [68]:
model.fit(X_train, Y_train)

LogisticRegression(solver='newton-cg')

In [69]:
model.score(X_train, Y_train)

0.9519230769230769

In [70]:
model.score(X_test, Y_test)

0.9615384615384616

In [71]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

0.9615384615384616
0.9615384615384616


In [72]:
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 96.15 %
Error: 3.85 %
