### 1. 

En el archivo "logistic_regression_digits" hemos visto un ejemplo multiclase. Elimina todas las imágenes y etiqueta (label) cuyo valor del label no sea 1 o 9. Es decir, elimina todos los dígitos y quédate solo con los dígitos 1 y 9.

Ahora, realiza un entrenamiento con logistic regression con los nuevos datos:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema (probar al menos 2 diferentes)

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

### No, no se mejora con dos únicas series de imágenes. El modelo es bastante más impreciso. El % de aciertos con la muestra de entrenamiento en el anterior modelo (64 columnas), era del 100% y en la muestra de test del 95.8%. Con solo dos columnas el % de aciertos con la muestra de entrenamiento es de: 20.4% y con la muestra de test del 18.3%

### La posibilidad de aprendizaje con menos modelos de imágenes es más baja

### Utilizando el parámetro 'liblinear' el porcentaje de aciertos empeora ligeramente y utilizando el parámetroo 'newton-cg' no mejora, se mantiene el porcentaje de aciertos del modelo inicial





In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
#from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb

In [2]:
from sklearn.datasets import load_digits
digits = load_digits() # 8x8 = 64 pixels  -- Very clean Dataset 

In [3]:
import pandas as pd
df = pd.DataFrame(data= np.c_[digits['data'], digits['target']])


In [105]:
df = df.iloc[:,[1,9,64]]

## Creamos el modelo

In [106]:
X = np.array(df.drop([64], axis=1))
y = np.array(df[64])
print(y.shape)
X.shape

(1797,)


(1797, 2)

In [120]:
model = linear_model.LogisticRegression(max_iter=150)
# No se está entrenado con el conjunto de entrenamiento
model.fit(X,y)
model.score(X, y)

0.2036727879799666

In [121]:
y_predict = model.predict(X)

### Validamos el modelo

In [122]:
seed =7
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=seed)

In [124]:
model = linear_model.LogisticRegression(max_iter=150)
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, x_train, y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())
print(cv_results)
print("----------")
print(msg)

[0.19832985 0.16701461 0.18371608]
----------
Logistic Regression: 0.183020 +- (0.012794)


In [125]:
model.fit(x_train, y_train)

LogisticRegression(max_iter=150)

In [115]:
model.score(x_train, y_train)

0.2045929018789144

In [127]:
model.score(x_test, y_test)

0.18333333333333332

In [129]:
predictions = model.predict(x_test)
print(model.score(X=x_test, y=y_test))
print(accuracy_score(y_test, predictions))

0.18333333333333332
0.18333333333333332


In [131]:
acierto = accuracy_score(y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 18.33 %
Error: 81.67 %


In [132]:
# matriz de confusión

import sklearn.metrics as metrics
y_pred = logisticRegr.predict(x_test)
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

[[ 6  0  0  0 26  0  0  0  0 11]
 [ 3  0  0  0 37  0  0  1  0  1]
 [ 0  0 16  7 10  2  0  0  0  5]
 [ 3  1  3  8 11  5  0  0  0  3]
 [ 0  0  0  0 36  0  0  0  0  1]
 [ 3  0  8  6  4  5  0  0  0  2]
 [ 1  0  0  0 27  0  0  0  0  0]
 [ 1  0  1  0 26  0  0  0  0  5]
 [ 2  1  2  5 24  0  0  0  0  9]
 [ 2  0  6  4 14  0  0  0  0  6]]


## Algoritmo alternativo para optimizar el modelo: liblinear

In [134]:
model = linear_model.LogisticRegression(max_iter=100, solver='liblinear')
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, x_train, y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())

In [135]:
model.fit(x_train, y_train)

LogisticRegression(solver='liblinear')

In [136]:
model.score(x_train, y_train)

0.19554627696590118

In [137]:
model.score(x_test, y_test)

0.1638888888888889

In [143]:
predictions = model.predict(x_test)
print(model.score(X=x_test, y=y_test))
print(accuracy_score(y_test, predictions))

0.1638888888888889
0.1638888888888889


In [145]:
acierto = accuracy_score(y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 16.39 %
Error: 83.61 %


## Otro algoritmo alternativo para optimizar el modelo: newton-cg

In [147]:
model = linear_model.LogisticRegression(max_iter=100, solver='newton-cg')
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, x_train, y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())

In [148]:
model.fit(x_train, y_train)

LogisticRegression(solver='newton-cg')

In [149]:
model.score(x_train, y_train)

0.2045929018789144

In [150]:
model.score(x_test, y_test)

0.18333333333333332

In [151]:
predictions = model.predict(x_test)
print(model.score(X=x_test, y=y_test))
print(accuracy_score(y_test, predictions))

0.18333333333333332
0.18333333333333332


In [152]:
acierto = accuracy_score(y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 18.33 %
Error: 81.67 %
