1. 

(X_train=80%)
(X_test=20%)

A partir del archivo "iris.csv" que se corresponde con datos relacionados con tres tipos de plantas (el target es el tipo de planta):

- Mediante regresión logística, predice qué planta se corresponde con los ejemplos: [[15.7,2.8,9.5,0.1]] y [[1.7,3.8,4.5,11.3]]
- ¿Qué acierto tiene tu modelo? (score)
- Utiliza un conjunto de test con el 40% de los datos: ¿cambian los resultados anteriores? ¿por qué?
- Elimina la clase "Virginica" de tus datos. Repite el proceso anterior, ¿cambian los resultados?
- ¿Consideras la regresión logística un buen algoritmo para estos datos? ¿por qué?

## Acierto del modelo

#### El modelo inicial con una muestra de test del 20% tiene un porcentaje de acierto de: 0.9916666666666667 para la muestra de entrenamiento y de: 0.8666666666666667 para la muestra de test

## Resultados con el 40% de muestra de test

#### Si utilizamos un conjunto de test con el 40% obtenemos un porcentaje de acierto para la muestra de entrenamiento de: 0.9777777777777777 y de: 0.9833333333333333

#### Sí cambia el porcentaje de acierto al modificar la muestra de test. Mejora el % de acierto con la muestra de test y disminuye ligeramente con la de entrenamiento. 

#### No tengo muy claro el por qué cambian pero creo que puede ser porque al ampliar la muestra de test, esta actúa también como entrenamiento mejorando las predicciones.

## Eliminar la clase Virgínica

#### Eliminando la clase Virgínica el porcentaje de aciertos con toda la base y al validar el modelo (entrenamiento: 80% y test: 20%) el porcentaje de aciertos es del 100% en ambos casos.

## ¿Es buen algoritmo?

#### Sí creo que se un buen algoritmo para predecir estos datos porque parece, por los resultados obtenidos que las variables independientes (longitud y anchura de pétalos y sépalos) permiten diferenciar muy bien el tipo de variedad. Se ajusta perfectamente a todas las variedades y en menor medida a la de Virgínica



In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
#from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb

In [3]:
import pandas as pd

df = pd.read_csv("../data/iris.csv", sep=',', header=0)
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [37]:
# Establecemos que columnas son variables independientes y cual dependiente
X = np.array(df.drop(['variety'], axis=1))
y = np.array(df['variety'])
print(y.shape)
X.shape

(150,)


(150, 4)

In [38]:
#Establecemos el modelo de regresion logística(tol=0.75, C=9)
model = linear_model.LogisticRegression(max_iter=150)
# Para todo el conjunto de datos
model.fit(X,y)
model.score(X, y)

0.9733333333333334

In [39]:
# la predicción de y se hará aplicando el modelo sobre las variables x
y_predict = model.predict(X)

In [40]:
# Obtenemos el porcentaje de aciertos del modelo
model.score(X,y)

0.9733333333333334

In [41]:
# Creamos un data frame con los valores a partir de los que queremos predecir la variable y
X_new = pd.DataFrame({'sepal.length': [15.7], 'sepal.width': [2.8], 'petal.length': [9.5], 'petal.width': [0.1]})
X_new

sepal.length  sepal.width  petal.length  petal.width
0          15.7          2.8           9.5          0.1

In [42]:
# aplicamos el modelos sobre el nuevo data frame con los valores para predecir (x_new) y obtenemos el valor predicho (y)
model.predict(X_new)

array(['Virginica'], dtype=object)

In [43]:
# Creamos un data frame con los valores a partir de los que queremos predecir la variable y
X_new_1 = pd.DataFrame({'sepal.length': [1.7], 'sepal.width': [3.8], 'petal.length': [4.5], 'petal.width': [11.3]})
X_new_1

sepal.length  sepal.width  petal.length  petal.width
0           1.7          3.8           4.5         11.3

In [44]:
model.predict(X_new_1)

array(['Virginica'], dtype=object)

## Validamos el modelo

In [31]:
# establecemos una muestra fija con una semilla y dividimos la base en entrenamiento (80%) y test (20%)
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)
print(X_train.shape)
X_test.shape

(120, 4)


(30, 4)

In [34]:
# Establecemos el modelo
model = linear_model.LogisticRegression(max_iter=150)
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())
print(cv_results)
print("----------")
print(msg)
print("----------")
print("----------")

[1.    0.975 1.   ]
----------
Logistic Regression: 0.991667 +- (0.011785)
----------
----------


In [45]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=150)

In [46]:
model.score(X_train, Y_train)

0.9916666666666667

In [47]:
model.score(X_test, Y_test)

0.8666666666666667

In [48]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

0.8666666666666667
0.8666666666666667


In [49]:
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 86.67 %
Error: 13.33 %


In [50]:
print(confusion_matrix(Y_test, predictions))

[[ 7  0  0]
 [ 0 10  2]
 [ 0  2  9]]


## Muestra de test del 40%

In [51]:
# establecemos una muestra fija con una semilla y dividimos la base en entrenamiento (80%) y test (20%)
seed = 9
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.4, random_state=seed)
print(X_train.shape)
X_test.shape

(90, 4)


(60, 4)

In [52]:
# Establecemos el modelo
model = linear_model.LogisticRegression(max_iter=150)
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())
print(cv_results)
print("----------")
print(msg)
print("----------")
print("----------")

[0.96666667 1.         0.96666667]
----------
Logistic Regression: 0.977778 +- (0.015713)
----------
----------


In [53]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=150)

In [54]:
model.score(X_train, Y_train)

0.9777777777777777

In [55]:
model.score(X_test, Y_test)

0.9833333333333333

In [56]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

0.9833333333333333
0.9833333333333333


In [57]:
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 98.33 %
Error: 1.67 %


In [58]:
print(confusion_matrix(Y_test, predictions))

[[22  0  0]
 [ 0 19  1]
 [ 0  0 18]]


## Elimino la clase Virgínica

In [60]:
 # Elimino la clase Virgínica
 df_1 = df.drop(df[df['variety']=='Virginica'].index)

In [62]:
X = np.array(df_1.drop(['variety'], axis=1))
y = np.array(df_1['variety'])
print(y.shape)
X.shape

(100,)


(100, 4)

In [63]:
#Establecemos el modelo de regresion logística(tol=0.75, C=9)
model = linear_model.LogisticRegression(max_iter=150)
# Para todo el conjunto de datos
model.fit(X,y)
model.score(X, y)

1.0

In [64]:
# la predicción de y se hará aplicando el modelo sobre las variables x
y_predict = model.predict(X)

In [65]:
model.score(X,y)

1.0

## Validamos el modelo con el nuevo dataframe sin la clase Virginica

In [66]:
seed = 7
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)
print(X_train.shape)
X_test.shape

(80, 4)


(20, 4)

In [67]:
# Establecemos el modelo
model = linear_model.LogisticRegression(max_iter=150)
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=3, random_state=None) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
# cross_val_score 
cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f %s (%f)" % (name, cv_results.mean(), "+-", cv_results.std())
print(cv_results)
print("----------")
print(msg)
print("----------")
print("----------")

[1. 1. 1.]
----------
Logistic Regression: 1.000000 +- (0.000000)
----------
----------


In [68]:
model.fit(X_train, Y_train)

LogisticRegression(max_iter=150)

In [69]:
model.score(X_train, Y_train)

1.0

In [70]:
model.score(X_test, Y_test)

1.0

In [71]:
predictions = model.predict(X_test)
print(model.score(X=X_test, y=Y_test))
print(accuracy_score(Y_test, predictions))

1.0
1.0


In [72]:
acierto = accuracy_score(Y_test, predictions)

error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 100.0 %
Error: 0.0 %


In [73]:
print(confusion_matrix(Y_test, predictions))

[[12  0]
 [ 0  8]]
